services:
  db:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: mysqlPW
    ports:
      - '3333:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./scripts/database/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: root:mysqlPW@tcp(db:3306)/db?charset=utf8mb4&parseTime=True&loc=Local
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./app.log:/app/app.log

  opensearch:
    image: opensearchproject/opensearch:2.4.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
    networks:
      - opensearch_net

  fluentd:
    build:
      dockerfile: Dockerfile.fluentd
    container_name: fluentd
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluent.conf
      - ./app.log:/fluentd/log/app.log  # Monta o diretório de logs do host no contêiner
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - opensearch
    networks:
      - opensearch_net

  dashboard:
    image: opensearchproject/opensearch-dashboards:2.4.0
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: "http://opensearch:9200"
    depends_on:
      - opensearch
    networks:
      - opensearch_net

volumes:
  mysql-volume:
networks:
  opensearch_net:
    driver: bridge