services:
  db:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: mysqlPW
    ports:
      - '3333:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./scripts/database/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    restart: always
    environment:
      DATABASE_URL: root:mysqlPW@tcp(db:3306)/db?charset=utf8mb4&parseTime=True&loc=Local
    ports:
      - "8080:8080"
    depends_on:
      - db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.1
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  mysql-volume:
networks:
  elk:
    driver: bridge