services:
  db:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: mysqlPW
    ports:
      - '3333:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./scripts/database/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    restart: always
    environment:
      DATABASE_URL: root:mysqlPW@tcp(db:3306)/db?charset=utf8mb4&parseTime=True&loc=Local
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  mysql-volume: